genericviews/urls.py
from django.urls import path
from genericviews import views

app_name = 'genericviews'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>', views.DetailsView.as_view(), name = 'detail'),
    path('edit/<int:pk>', views.EditView.as_view(), name = 'edit'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name = 'delete'),
    path('makeentry', views.CreateProductView.as_view(), name = 'makeentry'),
    path('deletemultiple', views.MultipleDeleteView.as_view(), name = 'multiple_delete'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('create', views.RegisterView.as_view(), name = 'register'),
    path('login', views.LoginView.as_view(), name = 'login'),
    path('reset', views.ResetPasswordView.as_view(), name = 'reset'),
    path('logout', views.logout_user, name = 'logout')
]

website/urls.py
from django.conf import settings
from django.urls import (
    path, 
    include
)
from django.conf.urls.static import static
from django.contrib import admin
from website import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.baseview, name = 'base'),
    path('genericviews/', include('genericviews.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genericviews/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(
            User,
            on_delete = models.CASCADE
        )
    title = models.CharField(max_length = 100)
    desc = models.CharField(max_length = 300)
    image = models.ImageField(null = True, blank = True, upload_to='.')

    def __str__(self):
        return self.title

genericviews/forms.py
from django import forms


class ProductForm(forms.Form):
    title = forms.CharField(label = 'Title', max_length = 100)
    desc = forms.CharField(label = 'Description', max_length = 300, help_text = 'Write a brief description', widget = forms.Textarea(
        attrs = {
            'cols': 20,
            'rows': 5
        }
    ))
    image = forms.ImageField()

genericviews/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import (
    render,
    HttpResponseRedirect, 
    reverse
)
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from genericviews.forms import ProductForm
from genericviews.models import Product

import logging

genericviews_logger = logging.getLogger(__name__)

# Create your views here.

class CreateProductView(LoginRequiredMixin, generic.FormView):
    model = Product
    form_class = ProductForm
    template_name = 'genericviews/makeentry.html'

    def get(self, request, *args, **kwargs):
        form = ProductForm()
        genericviews_logger.info('Product create form requested!! by user {0}...' .format(request.user))
        return render(request, 'genericviews/makeentry.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        title = form.data['title']
        desc = form.data['desc']

        Product.objects.create(
            user = request.user, 
            title = title, 
            desc = desc
        )

        form = ProductForm()

        messages.add_message(
            request, 
            messages.SUCCESS, 
            'You have successfully created a product!'
        )
        genericviews_logger.info('New product created by user {0}...' .format(request.user))
        return HttpResponseRedirect('/genericviews/')

class IndexView(LoginRequiredMixin, generic.ListView):
    model = Product
    context_object_name = 'product_list'
    template_name = 'genericviews/index.html'
    paginate_by = 2

    login_url = '/users/login'
    redirect_field_name = 'redirect_to'

    def get_queryset(self):
        empty_values_list = list(filter(lambda x: x == '', self.request.GET.values()))
        total_len = len(self.request.GET.keys()) - 1
        if len(empty_values_list) < total_len:
            # get datas from filter form
            genericviews_logger.info('Getting filter data for user {0}...' .format(self.request.user))

            record_id = self.request.GET.get('record-id', None)
            product_title = self.request.GET.get('product-title', None)

            if record_id and product_title:
                genericviews_logger.info('Product listing according to record id and product title for user {0}...' .format(self.request.user))
                return Product.objects.all().filter(user = self.request.user).filter(id = record_id).filter(title = product_title).order_by('id')
            elif record_id:
                genericviews_logger.info('Product listing according to record id for user {0}...' .format(self.request.user))
                return Product.objects.all().filter(user = self.request.user).filter(id = record_id).order_by('id')
            elif product_title:
                genericviews_logger.info('Product listing according to product title for user {0}...' .format(self.request.user))   
                return Product.objects.all().filter(user = self.request.user).filter(title = product_title).order_by('id')
        else:
            genericviews_logger.info('Product listing for user {0}...' .format(self.request.user))
            return Product.objects.all().filter(user = self.request.user).order_by('id')

    def get_paginate_by(self, queryset):
        if 'paginate_by' in self.request.GET:
            self.request.session['paginate_by'] = self.request.GET['paginate_by']
            self.paginate_by = self.request.session.get('paginate_by', self.paginate_by)
        elif 'page' in self.request.GET:
            self.paginate_by = self.request.session.get('paginate_by', self.paginate_by)
        else:
            if 'paginate_by' in self.request.session:
                del self.request.session['paginate_by']

        return self.paginate_by

class DetailsView(LoginRequiredMixin, generic.DetailView):
    model = Product
    template_name = 'genericviews/detail.html'

    login_url = '/users/login'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super(DetailsView, self).get_context_data(**kwargs)

        genericviews_logger.info('Product detail for product id {0} by user {1}...' .format(self.kwargs['pk'], self.request.user))

        context['new_list'] = Product.objects.all().filter(~Q(user = self.request.user)).order_by('id')

        return context

class EditView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    fields = ['title', 'desc']
    template_name_suffix = '_update_form'

    login_url = '/users/login'
    redirect_field_name = 'redirect_to'

    def get_success_url(self):
        messages.add_message(
            self.request, 
            messages.SUCCESS, 
            'You have successfully update the product!'
        )
        genericviews_logger.info('Product update successful for product id {0} by user {1}...' .format(self.kwargs['pk'], self.request.user))
        return reverse('genericviews:detail', kwargs = {'pk': self.kwargs['pk']})

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Product

    login_url = '/users/login'
    redirect_field_name = 'redirect_to'

    def get_success_url(self):
        pid = self.kwargs['pk']
        messages.add_message(
            self.request, 
            messages.SUCCESS, 
            'You have successfully deleted a product!'
        )
        genericviews_logger.info('Product {0} deleted by user {1}...' .format(pid, self.request.user))
        return reverse('genericviews:index')

class MultipleDeleteView(LoginRequiredMixin, generic.FormView):
    model = Product

    login_url = '/users/login'
    redirect_field_name = 'redirect_to'

    def post(self, request, *args, **kwargs):
        # get list of checkbox values
        product_ids = list(map(lambda id: int(id), request.POST.getlist('ids')))

        # delete rows from Product model having those ids
        prod_obj = Product.objects.filter(pk__in = product_ids).delete()
        
        # redirect to index page
        messages.add_message(
            request, 
            messages.SUCCESS, 
            'You have successfully deleted {0} product!' .format(len(product_ids))
        )
        genericviews_logger.info('Products deleted by user {0}...' .format(request.user))
        return HttpResponseRedirect('/genericviews/')

class FilterView(LoginRequiredMixin, generic.FormView):
    pass

templates/genericviews/base.html
{% load static %}

<html>
    <head>
        <title>
            {% block title %}
                Base
            {% endblock %}
        </title>
        {% block static %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            
            <link rel="stylesheet" type="text/css" href="{% static 'genericviews/css/bootstrap.css' %}" />
            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
            <link rel="stylesheet" type="text/css" href="{% static 'genericviews/css/style.css' %}" />
            <script src="{% static 'genericviews/js/jquery-3.2.1.min.js' %}"></script>
            <script src="{% static 'genericviews/js/tether.min.js' %}"></script>
            <script src="{% static 'genericviews/js/bootstrap.js' %}"></script>
        {% endblock %}
    </head>
    <body>
        {% block navbar %}
            <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% if request.user.is_authenticated %}
                    <a class="navbar-brand" href="#">Welcome, {{ request.user }}</a>
                {% else %}
                    <a class="navbar-brand" href="#">Howdy, stranger!</a>
                {% endif %}
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if not request.user.is_authenticated %}
                            <i class="fa fa-home" aria-hidden="true"></i>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'base' %}">Home</a>
                            </li>
                        {% else %}
                            <i class="fa fa-home" aria-hidden="true"></i>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'genericviews:index' %}">Home</a>
                            </li>
                        {% endif %}
                    </ul>
                    {% if not request.user.is_authenticated %}
                        <ul class="nav navbar-nav ml-auto">
                            <i class="fa fa-user-plus" aria-hidden="true"></i>
                            <li class="nav-item">
                                <a href="{% url 'users:register' %}">Register</a>
                            </li> &nbsp; | &nbsp;
                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                            <li class="nav-item">
                                <a href="{% url 'users:login' %}">Login</a>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav ml-auto">
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            <li class="nav-item">
                                <a href="{% url 'users:logout' %}">Logout</a>
                            </li>
                        </ul>
                    {% endif %}
                </div>
            </nav>
        {% endblock %}

        {% block content %}
            {% block breadcrumbs %}{% endblock %}
        {% endblock %}

        {% block javascript %}{% endblock %}
    </body>
</html>

templates/genericviews/detail.html
{% extends 'genericviews/base.html' %}


{% block title %}
	Detail Page
{% endblock %}

{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
			{% if not request.user.is_authenticated %}
				<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			{% else %}
				<li class="breadcrumb-item"><a href="{% url 'genericviews:index' %}">Home</a></li>
			{% endif %}
			<li class="breadcrumb-item active">Product Detail</li>
		</ol>
	{% endblock %}

	<div class="container-fluid">
		{% if messages %}
			<div class="alert alert-success" role="alert">
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
							<strong>{{ message }}</strong>
						</li>
					{% endfor %}
				</ul>
			</div>
		{% endif%}

		<div class="row">
			<div class="col-md-9">
				<h2><center>{{ product.title }}</center></h2> <br>

				{% if product.image %}
					<img src="{{ product.image.url }}" alt="..." class="img-fluid">
				{% else %}
					<center>Image not found!</center>
				{% endif %}

				<p class="lead">{{ product.desc }}</p>

				<br><p>Posted by: {{ product.user }}</p>
			</div>

			<div class="col-md-3">
				<h2 style="margin-top: 5px;"><center>Similar Products</center></h2> <br>

				<div class="list-group">
					{% for items in new_list %}
						<a href="{% url 'genericviews:detail' items.id %}" class="list-group-item list-group-item-action" style="background-color: black; color: white;">
							{{ items.title }}
						</a>
					{% endfor %}
				</div>
			</div>
		</div>
		
		<br>
		<a href="{% url 'genericviews:index' %}" class="btn btn-primary">Back to watch listings!</a>
	</div>
{% endblock %}

templates/genericviews/index.html
{% extends 'genericviews/base.html' %}


{% block title %}
	Index
{% endblock %}

{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
			{% if not request.user.is_authenticated %}
				<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			{% else %}
				<li class="breadcrumb-item"><a href="{% url 'genericviews:index' %}">Home</a></li>
			{% endif %}
			<li class="breadcrumb-item active">Product Listing</li>
		</ol>
	{% endblock %}

	<div class="container">
		{% if messages %}
			<div class="alert alert-success" role="alert">
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
							<strong>{{ message }}</strong>
						</li>
					{% endfor %}
				</ul>
			</div>
		{% endif %}

		<div class="row">
			<div class="col-6 col-sm-3">
				<form class="form-inline" action="{% url 'genericviews:index' %}" method="get">
					<div class="form-group">
						<select class="form-control" name="paginate_by" id='paginate_options'>
							<option value="5">5</option>
							<option value="10">10</option>
							<option value="15">15</option>
							<option value="20">20</option>
						</select>
					</div>
					<div class="form-group">
						<input class="form-control" type='submit' value='Choose!' style="width:90px;">
					</div>
				</form>
			</div>
			{% if product_list %}
				{% if is_paginated %}
					<nav aria-label="Page navigation example">
						<ul class="pagination justify-content-center">
							{% if page_obj.has_previous %}
								<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
							{% else %}
								<li class="disabled"><span>Previos</span></li>
							{% endif %}

							{% for i in page_obj.paginator.page_range %}
								{% if page_obj.number == i %}
									<li class="active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
								{% else %}
									<li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
								{% endif %}
							{% endfor %}

							{% if page_obj.has_next %}
								<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
							{% else %}
								<li class="disabled"><span>Next</span></li>
							{% endif %}
						</ul>
					</nav>
				{% endif %}
		</div>

		<div class="row">
			<div class="col"></div>
			<div class="col-6">
					<h1>Buy Wrist Watches!</h1>
			</div>
			<div class="col">
				<a href="{% url 'genericviews:makeentry' %}" style="color:inherit">
					<button type="button" class="btn btn-outline-success and-all-other-classes"> 
						Create New Product
					</button>
				</a>
			</div>					
		</div>

		<div class="row">
			<table class="table table-sm">			
				<tr>
					<th></th>
					<th>Record ID</th>
					<th>Titles</th>
					<th>Actions</th>
				</tr>
				<form action="{% url 'genericviews:multiple_delete' %}" method="POST">
					{% csrf_token %}
					{% for product in product_list %}
						<tr style="height: 20px;">
							<td><input type="checkbox" value={{ product.id }} name="ids"></td>
							<td>{{ product.id }}</td>
							<td><a href = "{% url 'genericviews:detail' product.id %}">{{ product.title }}</a></td>
							<td>
								<i class="fa fa-pencil" aria-hidden="true"></i>
								<a href="{% url 'genericviews:edit' product.id %}">Edit</a> | 
								<i class="fa fa-trash" aria-hidden="true"></i>
								<a href="{% url 'genericviews:delete' product.id %}">Delete</a>
							</td>
						</tr>
					{% endfor %}
					<input type="submit" value="Delete Selected" class="btn btn-outline-danger"> &nbsp; &nbsp;
				</form>

				<button type="button" class="btn btn-outline-success and-all-other-classes" data-toggle="modal" data-target="#filterModal">
					<i class="fa fa-filter" aria-hidden="true"></i>Filter
				</button>

				<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="filterModalLabel" aria-hidden="true">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="filterModalLabel" style="color: black;">New message</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<form action="{% url 'genericviews:index' %}" method="GET" id = 'filter-form'>
									{% csrf_token %}
									<div class="form-group">
										<label for="record-id" class="form-control-label" style="color: black;">Record ID:</label>
										<input type="text" class="form-control" name="record-id" id="rec-id">
									</div>
									<div class="form-group">
										<label for="product-title" class="form-control-label" style="color: black;">Title:</label>
										<input type="text" class="form-control" name="product-title" id="prod-title">
									</div>
									<div class="modal-footer">
										<p id="err-msg" style="color:red;">Fill at least one field!</p>
										<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
										<button type="button" class="btn btn-primary" onclick="validate()">Filter</button>
										<!-- <input type="submit" class="btn btn-primary" value="Filter"> -->
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>	
			</table>
		{% else %}
			<h3>No product found</h3>
			<div class="row">
				<div class="col"></div>
				<div class="col">
					<a href="{% url 'genericviews:makeentry' %}" style="color:inherit">
						<button type="button" class="btn btn-outline-success and-all-other-classes"> 
							Create New Product
						</button>
					</a>
				</div>					
			</div>
		{% endif %}
		</div>
	</div>		
{% endblock %}

{% block javascript %}
	<script type="text/javascript">
		$(function () {
			$('#err-msg').hide();
			$('#paginate_options').val({{ page_obj.paginator.per_page }});
		});

		function validate() {
			var record_id = $('#rec-id').val();
			var title = $('#prod-title').val();

			console.log(record_id, title);

			if (!record_id & !title){
				$('#err-msg').show();
				return false;
			} else {
				$('#filter-form').submit();
			}
		}
	</script>
{% endblock %}

templates/genericviews/makeentry.html
{% extends 'genericviews/base.html' %}

{% block title %}
	Product Entry
{% endblock %}
	
{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
            {% if not request.user.is_authenticated %}
				<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			{% else %}
				<li class="breadcrumb-item"><a href="{% url 'genericviews:index' %}">Home</a></li>
			{% endif %}
			<li class="breadcrumb-item active">Create New Product</li>
		</ol>
	{% endblock %}

	<div class="row">
		<div class="Absolute-Center is-Responsive">
			<div id="logo-container">Create New Product</div>
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <form action="{% url 'genericviews:makeentry' %}" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-header" aria-hidden="true"></i></span>
                            {{ form.title }}         
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
                            {{ form.desc }}
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-upload" aria-hidden="true"></i></span>
                            {{ form.image }}
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="submit" value="Create"></input>
                        </div>
                    </form>        
                </div>  
            </div>    
        </div>
    </div>
{% endblock %}

templates/genericviews/product_confirm_delete.html
{% extends 'genericviews/base.html' %}

{% block title %}
	Product Delete
{% endblock %}
	
{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
			{% if not request.user.is_authenticated %}
				<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			{% else %}
				<li class="breadcrumb-item"><a href="{% url 'genericviews:index' %}">Home</a></li>
			{% endif %}
			<li class="breadcrumb-item active">Delete Product</li>
		</ol>
	{% endblock %}

	<div class="container">
		<form class="form-inline" action = "" method = 'POST'>
			<div class="form-group">
				{% csrf_token %}
				<p>Are you sure you want to delete "{{ object }}"?</p>
                <input type="submit" value="Confirm" />
			</div>
		</form>
	</div>
{% endblock %}

templates/genericviews/product_update_form.html
{% extends 'genericviews/base.html' %}

{% block title %}
	Product Update
{% endblock %}
	
{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
			{% if not request.user.is_authenticated %}
				<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			{% else %}
				<li class="breadcrumb-item"><a href="{% url 'genericviews:index' %}">Home</a></li>
			{% endif %}
			<li class="breadcrumb-item active">Update Product</li>
		</ol>
	{% endblock %}

	<div class="row">
		<div class="Absolute-Center is-Responsive">
			<div id="logo-container">Update Product</div>
				<div class="col-sm-12 col-md-10 col-md-offset-1">
					<form action="{% url 'genericviews:edit' product.id %}" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="form-group input-group">
							<span class="input-group-addon"><i class="fa fa-header" aria-hidden="true"></i></span>
							{{ form.title }}         
						</div>
						<div class="form-group input-group">
							<span class="input-group-addon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
							{{ form.desc }}
						</div>
						<div class="form-group input-group">
							<!-- <span class="input-group-addon"><i class="fa fa-upload" aria-hidden="true"></i></span> -->
							{{ form.image }}
						</div>
						<div class="form-group">
							<input class="form-control" type="submit" value="Update"></input>
						</div>
					</form>        
				</div>  
			</div>    
		</div>
	</div>
{% endblock %}