genericviews/urls.py
from django.urls import path
from genericviews import views

app_name = 'genericviews'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>', views.DetailsView.as_view(), name = 'detail'),
    path('edit/<int:pk>', views.EditView.as_view(), name = 'edit'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name = 'delete'),
    path('makeentry', views.CreateProductView.as_view(), name = 'makeentry'),
    path('deletemultiple', views.MultipleDeleteView.as_view(), name = 'multiple_delete'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('create', views.RegisterView.as_view(), name = 'register'),
    path('login', views.LoginView.as_view(), name = 'login'),
    path('reset', views.ResetPasswordView.as_view(), name = 'reset'),
    path('logout', views.logout_user, name = 'logout')
]

website/urls.py
from django.conf import settings
from django.urls import (
    path, 
    include
)
from django.conf.urls.static import static
from django.contrib import admin
from website import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.baseview, name = 'base'),
    path('genericviews/', include('genericviews.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password', 'email']
        widgets = {
            'first_name': forms.TextInput({
                'placeholder': 'firstname'
            }),
            'last_name': forms.TextInput({
                'placeholder': 'lastname'
            }),
            'username': forms.TextInput({
                'placeholder': 'username'
            }),
            'email': forms.TextInput({
                'placeholder': 'email'
            }),
            'password': forms.PasswordInput({
                'placeholder': 'password'
            })
        }
    
    def save(self, commit = True):
        user = super(RegisterForm, self).save(commit = False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput({
                'placeholder': 'username'
            }),
            'password': forms.PasswordInput({
                'placeholder': 'password'
            })
        }

class ResetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput({
                'placeholder': 'username'
            }),
            'password': forms.PasswordInput({
                'placeholder': 'new password'
            })
        }

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.urls import (
    reverse, 
    reverse_lazy
)
from django.views.generic import FormView
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import (
    authenticate, 
    login,
    logout
)

from users.forms import (
    RegisterForm,
    LoginForm,
    ResetPasswordForm
)

import logging

users_logger = logging.getLogger(__name__)

# Create your views here.

class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'

    def get_success_url(self):
        messages.add_message(
            self.request, 
            messages.SUCCESS, 
            'You have successfully registered your account!'
        )
        users_logger.info('A user just registered..')
        return reverse('users:login')

class LoginView(FormView):
    model = User
    form_class = LoginForm
    template_name = 'users/login.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        username = form.data['username']
        password = form.data['password']

        user = authenticate(
            request, 
            username = username, 
            password = password
        )

        if user is not None:
            login(request, user)
            messages.add_message(
                self.request, 
                messages.SUCCESS, 
                'You have successfully logged in!'
            )
            users_logger.info('Logged in by user {0}..' .format(username))
            return HttpResponseRedirect('/genericviews/')
        else:
            messages.add_message(
                self.request, 
                messages.ERROR, 
                'Oops! Login Error'
            )
            users_logger.error('Login mismatch for user {0}..' .format(username))
            return HttpResponseRedirect('/users/login')

def logout_user(request):
    user = request.user
    messages.add_message(
        request, 
        messages.SUCCESS, 
        'You have successfully logged out!'
    )
    logout(request)
    users_logger.info('Logged out by user {0}..' .format(user))
    return HttpResponseRedirect('/users/login')

class ResetPasswordView(FormView):
    model = User
    form_class = ResetPasswordForm
    template_name = 'users/password_reset.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        username = form.data['username']
        password = form.data['password']

        try:
            user = User.objects.all().filter(username = username)[0]
            user.set_password(password)
            user.save()

            messages.add_message(
                self.request, 
                messages.SUCCESS, 
                'You have successfully changed your password!'
            )
            users_logger.info('Password changed by user {0}..' .format(username))
            return HttpResponseRedirect('/users/login')
        except:
            messages.add_message(
                self.request, 
                messages.ERROR, 
                'Oops! This user does not exist!'
            )
            users_logger.error('Password changed was not successfull for user {0}..' .format(username))
            return HttpResponseRedirect('/users/reset')

templates/users/login.html
{% extends 'genericviews/base.html' %}

{% block title %}
	Login
{% endblock %}
	
{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			<li class="breadcrumb-item active">Login</li>
		</ol>
	{% endblock %}

    <div class="container">
        {% if messages %}
			<div class="alert alert-success" role="alert">
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
							<strong>{{ message }}</strong>
						</li>
					{% endfor %}
				</ul>
			</div>
		{% endif %}
        
        <div class="row">
            <div class="Absolute-Center is-Responsive">
                <div id="logo-container">Login</div>
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <form action="" id="loginForm" method="POST">
                        {% csrf_token %}
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {{ form.username }}         
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            {{ form.password }}
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="submit" value="Login"></input>
                        </div>
                        <div class="form-group text-center">
                            <a href="#">Forgot Password</a>&nbsp;
                        </div>
                    </form>        
                </div>  
            </div>    
        </div>
    </div>
	
{% endblock %}

templates/users/password_reset.html
{% extends 'genericviews/base.html' %}

{% block title %}
    Reset Pasword
{% endblock %}
	
{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
            {% if not request.user.is_authenticated %}
                <li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url 'genericviews:index' %}">Home</a></li>
            {% endif %}
			<li class="breadcrumb-item active">Reset Pasword</li>
		</ol>
	{% endblock %}

    <div class="container">
        {% if messages %}
			<div class="alert alert-success" role="alert">
				<ul class="messages">
					{% for message in messages %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
							<strong>{{ message }}</strong>
						</li>
					{% endfor %}
				</ul>
			</div>
		{% endif %}
        
        <div class="row">
            <div class="Absolute-Center is-Responsive">
                <div id="logo-container">Change Password</div>
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {{ form.username }}         
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            {{ form.password }}
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="submit" value="Change Pasword"></input>
                        </div>
                    </form>        
                </div>  
            </div>    
        </div>
    </div>
	
{% endblock %}

templates/users/register.html
{% extends 'genericviews/base.html' %}

{% block title %}
	Register
{% endblock %}
	
{% block content %}
	{% block breadcrumbs %}
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
			<li class="breadcrumb-item active">Create New User</li>
		</ol>
    {% endblock %}
    
    <div class="container">
            <div class="row">
                <div class="Absolute-Center is-Responsive">
                    <div id="logo-container">Register</div>
                    <div class="col-sm-12 col-md-10 col-md-offset-1">
                        <form action="" id="registerForm" method="POST">
                            {% csrf_token %}
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                {{ form.username }}          
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                {{ form.password }}
                            </div>
                            <div class="form-group input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="submit" value="Register"></input>
                            </div>
                        </form>        
                    </div>  
                </div>    
            </div>
        </div>
{% endblock %}